// src/app/privacy-policy/page.tsx
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy | Squiggles',
  description: 'Read the Squiggles Privacy Policy to understand how we handle your data.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="container mx-auto py-12 px-4 max-w-3xl">
      <h1 className="text-3xl md:text-4xl font-bold text-primary mb-8 text-center">Privacy Policy</h1>
      
      <section className="space-y-6 text-muted-foreground">
        <p className="italic">Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <h2 className="text-2xl font-semibold text-foreground pt-4">1. Introduction</h2>
        <p>Welcome to Squiggles ("we," "us," or "our"). We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our application Squiggles (the "Service"). Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the service.</p>

        <h2 className="text-2xl font-semibold text-foreground pt-4">2. Information We Collect</h2>
        <p>We may collect information about you in a variety of ways. The information we may collect via the Service includes:</p>
        <ul className="list-disc list-inside space-y-2 pl-4">
          <li>
            <strong>Personal Data:</strong> Personally identifiable information, such as your email address, display name, and unique funny username that you provide when you register with the Service or that is generated for you. If you sign in via Google, we may collect your name, email, and profile picture as provided by Google.
          </li>
          <li>
            <strong>User-Generated Content:</strong> The drawings you create on our canvas ("Original Drawings") and the images generated by our AI from those drawings ("Transformed Images"). If you choose to publish your creations to our Public Gallery, these will be visible to other users.
          </li>
          <li>
            <strong>Derivative Data:</strong> Information our servers automatically collect when you access the Service, such as your IP address, browser type, operating system, access times, and the pages you have viewed directly before and after accessing the Service. This is standard for most web services.
          </li>
          <li>
            <strong>Financial Data:</strong> If you purchase credits, we use a third-party payment processor (Stripe) to handle payments. We do not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.
          </li>
           <li>
            <strong>Cookies and Local Storage:</strong> We may use cookies and local storage to help customize the Service and improve your experience (e.g., remembering your theme preference).
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-foreground pt-4">3. How We Use Your Information</h2>
        <p>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Service to:</p>
        <ul className="list-disc list-inside space-y-2 pl-4">
          <li>Create and manage your account.</li>
          <li>Process your Original Drawings to generate Transformed Images using AI services.</li>
          <li>Enable user-to-user interactions (e.g., Public Gallery).</li>
          <li>Fulfill and manage purchases, orders, payments, and other transactions related to the Service.</li>
          <li>Monitor and analyze usage and trends to improve your experience with the Service.</li>
          <li>Notify you of updates to the Service.</li>
          <li>Respond to customer service requests.</li>
          <li>Administer promotions and contests.</li>
          <li>Prevent fraudulent transactions, monitor against theft, and protect against criminal activity.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-foreground pt-4">4. Disclosure of Your Information</h2>
        <p>We may share information we have collected about you in certain situations. Your information may be disclosed as follows:</p>
        <ul className="list-disc list-inside space-y-2 pl-4">
          <li>
            <strong>By Law or to Protect Rights:</strong> If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.
          </li>
          <li>
            <strong>Third-Party Service Providers:</strong> We may share your information with third parties that perform services for us or on our behalf, including payment processing (Stripe), data analysis, AI image generation (Google AI), email delivery, hosting services (Firebase), customer service, and marketing assistance.
          </li>
          <li>
            <strong>Public Gallery:</strong> If you choose to publish your creations, the Transformed Images and associated non-personally identifiable information (like style) will be visible to other users of the Service. Your funny username might also be displayed.
          </li>
          <li>
            <strong>Business Transfers:</strong> We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold text-foreground pt-4">5. Data Security</h2>
        <p>We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.</p>

        <h2 className="text-2xl font-semibold text-foreground pt-4">6. Data Retention</h2>
        <p>We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.</p>

        <h2 className="text-2xl font-semibold text-foreground pt-4">7. Children's Privacy</h2>
        <p>Squiggles is designed to be a fun and creative application for children. However, account creation, management, and any purchases of credits must be handled by a parent or legal guardian. We do not knowingly collect personally identifiable information from children under the age of 13 (or the relevant age in your jurisdiction) without parental consent. If you are a parent or guardian and you are aware that your child has provided us with Personal Data without your consent, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

        <h2 className="text-2xl font-semibold text-foreground pt-4">8. Your Choices Regarding Your Information</h2>
        <p>You may at any time review or change the information in your account or terminate your account by:</p>
        <ul className="list-disc list-inside space-y-2 pl-4">
          <li>Logging into your account settings and updating your account (functionality may be limited).</li>
          <li>Contacting us using the contact information provided below to request account deletion.</li>
        </ul>
        <p>Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, some information may be retained in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Service and/or comply with legal requirements.</p>

        <h2 className="text-2xl font-semibold text-foreground pt-4">9. Changes to This Privacy Policy</h2>
        <p>We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

        <h2 className="text-2xl font-semibold text-foreground pt-4">10. Contact Us</h2>
        <p>If you have questions or comments about this Privacy Policy, please contact Mr. Squiggles at:</p>
        <p>squiggles.ai@gmail.com</p>
      </section>
    </div>
  );
}
